In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle

In [11]:
sizes= np.random.randint(500,35000,100)


In [10]:
sizes


array([ 6545, 27572, 22601, 30017, 27492,  8869, 31368, 29613, 13964,
       33783, 34875, 15616, 21724, 32146, 13392, 22859,  6478, 12711,
       17469, 13338, 13356, 25882, 11550,  3018, 28290,  4640,  2283,
       22629,  6428, 11217, 26496, 28639,  3946, 20219, 17450, 14836,
       20254, 31585,  9393, 17243, 16275, 16460, 15189, 25400, 23783,
       33532, 20615,  6550,  6310,  9350,  3867, 10436, 17306, 14482,
       33265, 17608, 24286, 22646, 12772, 10587, 34584, 31569,  6917,
       23422, 28816,  6203, 23693, 12651,  6278, 11771, 34392, 34313,
       21091, 24537, 14356,   621, 28685, 24113, 21077, 31424,  9497,
       24293, 19086, 11581, 21797, 23734, 24318, 14459, 13829, 18613,
       12698, 31970, 30850,  6080, 14305,  5977,  7253, 13873, 31881,
       14100], dtype=int32)

In [13]:
bedrooms=np.random.randint(1,6,100)

In [14]:
len(bedrooms)

100

In [19]:
prices = (sizes*0.3)+(bedrooms*50)+np.random.randint(-200,200,100)

In [20]:
prices

array([ 1459.8,  6604.1,  6572.4,  5795.9,  5492.1,  4350.1,  1929.3,
        9264.6,  5385.5,  3598.2,  9779.3,  7162.6,  1483.6,  8575. ,
         657.9,  9092.1,  5449.3,  5630.1,  4419.7,  8564.2,  7973.6,
        4915.9,  1045.2,  2423.4,  6148.1,  9399.4,  1309.7,  3694.2,
        6104.6,  3453.1,  1346.2,  5639.9, 10270.6,  1400.2,  1889.1,
        7315.1,  7723.3,  9730.8,  9928.2,  4688.4,  7646.2,  4624.8,
        7624.9,  6796.3,   954.2,  9468.5,  3166.6,  1926.7,  9720.7,
       10314.4,  9749.5, 10102.6,  2520.8,  4170.5,  6107.3,  9644.1,
        9990.9,  2789.7,  1782.1,  5250.5,  5625. ,  3785.7,  2359.2,
        9368.9,  2708.3,  6226.5,  4950.7,  4161.5,  5148.9,  1480.4,
        2626.8,  5675.9,  3846.3,  1265.2,  3677.2,  1964.2,  8289. ,
        1937.9,  9745.5,  6558. ,  7224.5,  3636.1,  4106.8,  9456.2,
        9536.9,  7143.3,  5164.5,   843.5,  6253.3,   335. ,  2341.9,
        9512.4,  7716.7,  5255.4,  4817.9,  8461.2, 10119.1,  2214.4,
        8599.7,  476

In [22]:
data=pd.DataFrame({
    "sizes_sqft" :sizes,
    "bedrooms":bedrooms,
    "prices":prices

})

In [23]:
data.head()

,sizes_sqft,bedrooms,prices
0,4866,2,1459.8
1,22017,2,6604.1
2,21198,2,6572.4
3,18933,3,5795.9
4,18537,2,5492.1


In [28]:
x = data[["sizes_sqft", "bedrooms"]]


In [24]:
y=data["prices"]

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x,y)

In [ ]:
sample_x=np.array([[2000,3],[1500,2]])


In [32]:
model = LinearRegression()
model.fit(x, y)
sample_x=np.array([[2000,3],[1500,2]])
model.predict(sample_x)

c:\Users\Ankita\house prediction FastAPI\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([747.11095981, 543.20702111])

In [33]:
with open("house_price_model.pkl","wb")as f:
    pickle.dump(model,f)